# Generated by Django 6.0.2 on 2026-03-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_question_alter_lesson_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='enrolled_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='enrolled_at',
            new_name='created_at',
        ),
    ]
